version: "3.8"

services:

  redis:
    image: "redis:7.0.11"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3.12.4-management"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq